- name: terminate relative asg
  ec2_asg:
    name: "{{ relative }}"
    state: absent
    region: "{{ region }}"
  register: result

- name: terminate relative launch_config
  ec2_lc:
    name: "{{ result.launch_config_name }}"
    region: "{{ region }}"
    state: absent
